name: Build and Test Pipeline

on:
  push:
    branches:
      - '*'  # Pour tous les pushs sur les branches
    tags:
      - '*'  # Pour tous les pushs de tags

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "SALT_PASSWORD=${{ secrets.SALT_PASSWORD }}" >> .env
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> .env

      - name: Login to DockerHub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Development Docker Image
        run: docker build --target dev -t imt-dashboard-app-dev .

      - name: Run Tests
        run: |
          docker run --rm --env-file .env imt-dashboard-app-dev npm run test

      - name: Build Production Docker Image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: docker build --target prod -t imt-dashboard-app .

      - name: Determine Tag for Docker Image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: get_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Tag Docker Image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag imt-dashboard-app ${{ secrets.DOCKER_USERNAME }}/imt-dashboard-app:${{ env.RELEASE_TAG }}

      - name: Push Docker Image to DockerHub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/imt-dashboard-app:${{ env.RELEASE_TAG }}
